"""initial

Revision ID: d2576c1d1c5a
Revises: 
Create Date: 2018-01-09 10:08:50.236336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2576c1d1c5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('friendhip',
    sa.Column('friendship_id', sa.String(length=32), nullable=False),
    sa.Column('user_id_1', sa.String(length=32), nullable=True),
    sa.Column('user_id_2', sa.String(length=32), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_1'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['user_id_2'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('friendship_id')
    )
    op.create_index(op.f('ix_friendhip_user_id_1'), 'friendhip', ['user_id_1'], unique=False)
    op.create_index(op.f('ix_friendhip_user_id_2'), 'friendhip', ['user_id_2'], unique=False)
    op.create_table('list',
    sa.Column('list_id', sa.String(length=32), nullable=False),
    sa.Column('list_name', sa.String(length=32), nullable=True),
    sa.Column('creator_id', sa.String(length=32), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('list_id')
    )
    op.create_index(op.f('ix_list_list_name'), 'list', ['list_name'], unique=False)
    op.create_table('list_item',
    sa.Column('list_id', sa.String(length=32), nullable=True),
    sa.Column('list_item_id', sa.String(length=32), nullable=False),
    sa.Column('item_name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('link_url', sa.String(length=256), nullable=True),
    sa.Column('purchaser_id', sa.String(length=32), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['list.list_id'], ),
    sa.ForeignKeyConstraint(['purchaser_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('list_item_id')
    )
    op.create_index(op.f('ix_list_item_item_name'), 'list_item', ['item_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_list_item_item_name'), table_name='list_item')
    op.drop_table('list_item')
    op.drop_index(op.f('ix_list_list_name'), table_name='list')
    op.drop_table('list')
    op.drop_index(op.f('ix_friendhip_user_id_2'), table_name='friendhip')
    op.drop_index(op.f('ix_friendhip_user_id_1'), table_name='friendhip')
    op.drop_table('friendhip')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
